//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod bookmark;
pub mod note_categories;
pub mod notes;
pub mod notifications;
pub mod prelude;
pub mod recycle_bin;
pub mod reminder;
pub mod sea_orm_active_enums;
pub mod snippets;
pub mod sync_queue;
pub mod todo;
pub mod user_preferences;
pub mod workspace_preferences;
pub mod workspaces;
