//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "item_type")]
pub enum ItemType {
    #[sea_orm(string_value = "todo")]
    Todo,
    #[sea_orm(string_value = "note")]
    Note,
    #[sea_orm(string_value = "reminder")]
    Reminder,
    #[sea_orm(string_value = "snippet")]
    Snippet,
    #[sea_orm(string_value = "bookmark")]
    Bookmark,
    #[sea_orm(string_value = "workspace")]
    Workspace,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "notification_type")]
pub enum NotificationType {
    #[sea_orm(string_value = "backup_failed")]
    BackupFailed,
    #[sea_orm(string_value = "backup_success")]
    BackupSuccess,
    #[sea_orm(string_value = "workspace_invite_received")]
    WorkspaceInviteReceived,
    #[sea_orm(string_value = "workspace_invite_accepted")]
    WorkspaceInviteAccepted,
    #[sea_orm(string_value = "workspace_invite_declined")]
    WorkspaceInviteDeclined,
    #[sea_orm(string_value = "item_shared")]
    ItemShared,
    #[sea_orm(string_value = "item_unshared")]
    ItemUnshared,
    #[sea_orm(string_value = "item_updated")]
    ItemUpdated,
    #[sea_orm(string_value = "item_deleted")]
    ItemDeleted,
    #[sea_orm(string_value = "item_access_granted")]
    ItemAccessGranted,
    #[sea_orm(string_value = "item_access_revoked")]
    ItemAccessRevoked,
    #[sea_orm(string_value = "generic")]
    Generic,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "priority")]
pub enum Priority {
    #[sea_orm(string_value = "high")]
    High,
    #[sea_orm(string_value = "medium")]
    Medium,
    #[sea_orm(string_value = "low")]
    Low,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tag")]
pub enum Tag {
    #[sea_orm(string_value = "development")]
    Development,
    #[sea_orm(string_value = "inspiration")]
    Inspiration,
    #[sea_orm(string_value = "design")]
    Design,
    #[sea_orm(string_value = "research")]
    Research,
}
