//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspaces")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub name: String,
    pub description: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub is_default: i8,
    pub is_hidden: i8,
    pub is_secured: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookmark::Entity")]
    Bookmark,
    #[sea_orm(has_many = "super::notes::Entity")]
    Notes,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::recycle_bin::Entity")]
    RecycleBin,
    #[sea_orm(has_many = "super::reminder::Entity")]
    Reminder,
    #[sea_orm(has_many = "super::snippets::Entity")]
    Snippets,
    #[sea_orm(has_many = "super::todo::Entity")]
    Todo,
    #[sea_orm(has_many = "super::workspace_preferences::Entity")]
    WorkspacePreferences,
}

impl Related<super::bookmark::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookmark.def()
    }
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notes.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::recycle_bin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecycleBin.def()
    }
}

impl Related<super::reminder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reminder.def()
    }
}

impl Related<super::snippets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Snippets.def()
    }
}

impl Related<super::todo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todo.def()
    }
}

impl Related<super::workspace_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspacePreferences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
