//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod bookmark;
pub mod note_categories;
pub mod notes;
pub mod ollama_conversation_history;
pub mod ollama_conversation_prompt;
pub mod ollama_conversation_response;
pub mod prelude;
pub mod recycle_bin;
pub mod reminder;
pub mod snippets;
pub mod sync_queue;
pub mod todo;
pub mod user_preference;
pub mod workspaces;
