//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::bookmark::Entity as Bookmark;
pub use super::note_categories::Entity as NoteCategories;
pub use super::notes::Entity as Notes;
pub use super::recycle_bin::Entity as RecycleBin;
pub use super::reminder::Entity as Reminder;
pub use super::snippets::Entity as Snippets;
pub use super::sync_queue::Entity as SyncQueue;
pub use super::todo::Entity as Todo;
pub use super::user_preferences::Entity as UserPreferences;
pub use super::workspace_preferences::Entity as WorkspacePreferences;
pub use super::workspaces::Entity as Workspaces;
