//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod bookmark;
pub mod note_categories;
pub mod notes;
pub mod ollama_conversation_history;
pub mod ollama_conversation_prompt;
pub mod ollama_conversation_response;
pub mod prelude;
pub mod recycle_bin;
pub mod reminder;
pub mod sea_orm_active_enums;
pub mod snippets;
pub mod sync_queue;
pub mod todo;
pub mod user_preference;
pub mod workspaces;

seaography::register_entity_modules!([
    bookmark,
    note_categories,
    notes,
    ollama_conversation_history,
    ollama_conversation_prompt,
    ollama_conversation_response,
    recycle_bin,
    reminder,
    snippets,
    sync_queue,
    todo,
    user_preference,
    workspaces,
]);
seaography::register_active_enums!([
    sea_orm_active_enums::ItemType,
    sea_orm_active_enums::Priority,
    sea_orm_active_enums::Tag,
]);
