//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::ItemType;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "recycle_bin")]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "recycle_bin.ts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: Uuid,
    pub item_id: Uuid,
    pub item_type: ItemType,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub deleted_at: DateTimeWithTimeZone,
    pub workspace_identifier: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "Column::WorkspaceIdentifier",
        to = "super::workspaces::Column::Identifier",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Workspaces,
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::workspaces::Entity")]
    Workspaces,
}
