//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "item_type")]
#[ts(export, export_to = "sea_orm_active_enums.ts")]
pub enum ItemType {
    #[sea_orm(string_value = "todo")]
    Todo,
    #[sea_orm(string_value = "note")]
    Note,
    #[sea_orm(string_value = "reminder")]
    Reminder,
    #[sea_orm(string_value = "snippet")]
    Snippet,
    #[sea_orm(string_value = "bookmark")]
    Bookmark,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "priority")]
#[ts(export, export_to = "sea_orm_active_enums.ts")]
pub enum Priority {
    #[sea_orm(string_value = "high")]
    High,
    #[sea_orm(string_value = "medium")]
    Medium,
    #[sea_orm(string_value = "low")]
    Low,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tag")]
#[ts(export, export_to = "sea_orm_active_enums.ts")]
pub enum Tag {
    #[sea_orm(string_value = "development")]
    Development,
    #[sea_orm(string_value = "inspiration")]
    Inspiration,
    #[sea_orm(string_value = "design")]
    Design,
    #[sea_orm(string_value = "research")]
    Research,
}
