// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationType } from "./sea_orm_active_enums";

export type Model = {
  identifier: string;
  title: string;
  body: string;
  notificationType: NotificationType;
  createdAt: string;
  updatedAt: string;
  isRead: boolean;
  workspaceIdentifier: string | null;
};
