// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemType = "Todo" | "Note" | "Reminder" | "Snippet" | "Bookmark";

export type NotificationType =
  | "BackupFailed"
  | "BackupSuccess"
  | "WorkspaceInviteReceived"
  | "WorkspaceInviteAccepted"
  | "WorkspaceInviteDeclined"
  | "ItemShared"
  | "ItemUnshared"
  | "ItemUpdated"
  | "ItemDeleted"
  | "ItemAccessGranted"
  | "ItemAccessRevoked"
  | "Generic";

export type Priority = "High" | "Medium" | "Low";

export type Tag = "Development" | "Inspiration" | "Design" | "Research";
