#!/usr/bin/env lua
--[[
1. Rewrites bare #[ts(export)] in SeaORM-generated entity files to
   #[ts(export, export_to = "<stem>.ts")] so ts-rs emits per-file bindings.
2. Regenerates kernel/index.ts re-exporting all binding types so the package
   can be consumed via a path install ("kernel": "file:../kernel").

Usage (from inside kernel/):
    lua ../scripts/fix-ts-exports.lua [entities_dir]

entities_dir defaults to src/entities/postgres.
index.ts is always written to the current working directory.
--]]

local SKIP = { mod = true, prelude = true }

local SPECIAL = {
    sea_orm_active_enums = { "ItemType", "Priority", "Tag" },
}

local function to_pascal(stem)
    return (stem:gsub("_(%w)", function(w) return w:upper() end):gsub("^%l", string.upper))
end

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    return content
end

local function write_file(path, content)
    local f = assert(io.open(path, "w"))
    f:write(content)
    f:close()
end

local function stem(path)
    return path:match("([^/\\]+)%.rs$")
end

local function fix_file(path)
    local s = stem(path)
    local replacement = string.format('#[ts(export, export_to = "%s.ts")]', s)
    local original = read_file(path)
    if not original then return false end
    local updated = original:gsub("#%[ts%(export%)%]", replacement)
    if updated == original then return false end
    write_file(path, updated)
    return true
end

local function glob_rs(dir)
    local files = {}
    local handle = io.popen(string.format('find "%s" -maxdepth 1 -name "*.rs" | sort', dir))
    if not handle then return files end
    for line in handle:lines() do
        files[#files + 1] = line
    end
    handle:close()
    return files
end

local function generate_index(entities_dir)
    local header = "// Auto-generated by scripts/fix-ts-exports.lua — do not edit manually.\n"
    local special_exports = {}
    local imports = {}
    local interfaces = {}

    for _, path in ipairs(glob_rs(entities_dir)) do
        local s = stem(path)
        if s and not SKIP[s] then
            local binding_path = string.format("./bindings/%s", s)
            if SPECIAL[s] then
                local names = table.concat(SPECIAL[s], ", ")
                special_exports[#special_exports + 1] =
                    string.format('export type { %s } from "%s";\n', names, binding_path)
            else
                local type_name = to_pascal(s)
                imports[#imports + 1] =
                    string.format('import type { Model as %sModel } from "%s";\n', type_name, binding_path)
                interfaces[#interfaces + 1] =
                    string.format("export interface %s extends %sModel {}\n", type_name, type_name)
            end
        end
    end

    special_exports[#special_exports + 1] =
        'export type { JsonValue } from "./bindings/serde_json/JsonValue";\n'

    local lines = { header }
    for _, l in ipairs(special_exports) do lines[#lines + 1] = l end
    lines[#lines + 1] = "\n"
    for _, l in ipairs(imports) do lines[#lines + 1] = l end
    lines[#lines + 1] = "\n"
    for _, l in ipairs(interfaces) do lines[#lines + 1] = l end

    write_file("index.ts", table.concat(lines))
    io.write(string.format("  wrote: index.ts (%d interfaces, %d type exports)\n",
        #imports, #special_exports))
end

local function main()
    local entities_dir = arg[1] or "src/entities/postgres"

    if os.execute(string.format('test -d "%s"', entities_dir)) ~= 0 then
        io.stderr:write(string.format("error: directory not found: %s\n", entities_dir))
        os.exit(1)
    end

    local rs_files = glob_rs(entities_dir)
    local changed = {}
    for _, path in ipairs(rs_files) do
        if fix_file(path) then
            changed[#changed + 1] = path
        end
    end

    if #changed > 0 then
        for _, f in ipairs(changed) do
            io.write(string.format("  patched: %s\n", f))
        end
    else
        io.write("  nothing to patch (no bare #[ts(export)] found)\n")
    end

    generate_index(entities_dir)
end

main()
