#!/usr/bin/env python3
"""
1. Rewrites bare #[ts(export)] in SeaORM-generated entity files to
   #[ts(export, export_to = "<stem>.ts")] so ts-rs emits per-file bindings.
2. Regenerates kernel/index.ts re-exporting all binding types so the package
   can be consumed via a path install ("kernel": "file:../kernel").

Usage (from inside kernel/):
    python3 ../scripts/fix-ts-exports.py [entities_dir]

entities_dir defaults to src/entities/postgres.
index.ts is always written to the current working directory.
"""

import re
import sys
from pathlib import Path

PATTERN = re.compile(r'#\[ts\(export\)\]')

SKIP = {"mod", "prelude"}

# Files whose bindings don't follow the standard `Model` export pattern.
SPECIAL: dict[str, list[str]] = {
    "sea_orm_active_enums": ["ItemType", "Priority", "Tag"],
}


def to_pascal(stem: str) -> str:
    return "".join(w.capitalize() for w in stem.split("_"))


def fix_file(path: Path) -> bool:
    stem = path.stem
    replacement = f'#[ts(export, export_to = "{stem}.ts")]'
    original = path.read_text(encoding="utf-8")
    updated = PATTERN.sub(replacement, original)
    if updated == original:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def generate_index(entities_dir: Path) -> None:
    header = ["// Auto-generated by scripts/fix-ts-exports.py — do not edit manually.\n"]
    special_exports: list[str] = []
    imports: list[str] = []
    interfaces: list[str] = []

    for rs_file in sorted(entities_dir.glob("*.rs")):
        stem = rs_file.stem
        if stem in SKIP:
            continue

        binding_path = f"./bindings/{stem}"

        if stem in SPECIAL:
            names = ", ".join(SPECIAL[stem])
            special_exports.append(f'export type {{ {names} }} from "{binding_path}";\n')
        else:
            type_name = to_pascal(stem)
            imports.append(
                f'import type {{ Model as {type_name}Model }} from "{binding_path}";\n'
            )
            interfaces.append(
                f"export interface {type_name} extends {type_name}Model {{}}\n"
            )

    special_exports.append(
        'export type { JsonValue } from "./bindings/serde_json/JsonValue";\n'
    )

    lines = header + special_exports + ["\n"] + imports + ["\n"] + interfaces

    index_path = Path("index.ts")
    index_path.write_text("".join(lines), encoding="utf-8")
    print(f"  wrote: {index_path} ({len(imports)} interfaces, {len(special_exports)} type exports)")


def main() -> None:
    entities_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("src/entities/postgres")

    if not entities_dir.exists():
        print(f"error: directory not found: {entities_dir}", file=sys.stderr)
        sys.exit(1)

    changed = [f for f in sorted(entities_dir.glob("*.rs")) if fix_file(f)]

    if changed:
        for f in changed:
            print(f"  patched: {f}")
    else:
        print("  nothing to patch (no bare #[ts(export)] found)")

    generate_index(entities_dir)


if __name__ == "__main__":
    main()
