//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::countries::Entity as Countries;
pub use super::invitation::Entity as Invitation;
pub use super::one_time_passwords::Entity as OneTimePasswords;
pub use super::revoked_tokens::Entity as RevokedTokens;
pub use super::users::Entity as Users;
