//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: Uuid,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub profile_picture: Option<String>,
    #[sea_orm(unique)]
    pub username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::one_time_passwords::Entity")]
    OneTimePasswords,
    #[sea_orm(has_many = "super::revoked_tokens::Entity")]
    RevokedTokens,
}

impl Related<super::one_time_passwords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OneTimePasswords.def()
    }
}

impl Related<super::revoked_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RevokedTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
